format = """\
$os\
$username\
$directory\
$git_branch\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
$line_break$character"""

# Disable the blank line at the beginning of the prompt
add_newline = true

# Command timeout
command_timeout = 3600000

# color and style settings
palette = "kanagawa"

[fill]
symbol = ' '

[palettes.kanagawa]
arrow = "#FF5D62"      # ia: deep red from kanagawa
os = "#7E9CD8"         # va: soft blue from kanagawa
directory = "#957FB8"  # ca: muted purple from kanagawa
git = "#FF5D62"        # ia: deep red (mismo que arrow para consistencia)
duration = "#957FB8"   # ca: muted purple (mismo que directory)
text_color = "#DCD7BA" # na: warm white from kanagawa
text_light = "#1F1F28" # bl: deep background from kanagawa

[os]
disabled = false
style = "fg:#7E9CD8"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = " 󰣇  "
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[line_break]
disabled = false
# icon for the prompt
[character]
success_symbol = '[ 󰮯 ](bold fg:#E6C384)' # in dark pink tone
error_symbol = "[  ](bold fg:#223249)"       # in red if there is an error

# User settings
[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[$user](fg:#E82424	) ' # Symbol before the username
disabled = false
show_always = true

# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "                           # Branch with oriental touch

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text_color bg:git"

[docker_context]
disabled = true
symbol = " "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))](fg:#FF9E3B)($style)'
symbol = " "
version_format = "${raw}"

[java]
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:#FFA066)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:#DCD7BA)]($style)'
disabled = false

[nodejs]
symbol = " "
format = '[[ $symbol ($version) ](fg:#87a987)]($style)'

[rust]
symbol = " "
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'

[golang]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'

[php]
symbol = " "
format = '[[ $symbol ($version) ](fg:#FF9E3B)]($style)'

[time]
disabled = false
time_format = "%R"                            # Hour:Minute Format
format = '[[   $time ](fg:#8BA4B0)]($style)'
